# Generated by Django 6.0.2 on 2026-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userprofile_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymealentry',
            name='is_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
