# Generated by Django 6.0.2 on 2026-03-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_thyroid_condition_userprofile_thyroid_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
