# Generated by Django 6.0.2 on 2026-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_dailymealentry_is_eaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymealentry',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
