# Generated by Django 6.0.2 on 2026-03-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_dailymealentry_is_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
